public class Operator {
    public static void main(String[] args) {
        // Arithmatic Operators

        int a=5,b=10;

        System.out.println(a+b);
        System.out.println(a-b);
        System.out.println(a*b);
        System.out.println(a/b);
        System.out.println(a%b);


        System.out.println(a++);
        System.out.println(++b);

        System.out.println(a--);
        System.out.println(a--);

    }
}